#!/usr/bin/env python3
"""Check project state for EgoWorld Stage 1.

Run from the main .venv environment with:

    python scripts/check_project_state.py

This script checks file existence, main environment imports, and HaMeR environment imports.
It is read-only by default; pass --write-report to save outputs/environment_report.md.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_MARKDOWN = PROJECT_ROOT / "outputs" / "environment_report.md"

MAIN_IMPORTS = ["numpy", "cv2", "open3d", "mediapipe", "moge"]
HAMER_IMPORTS = ["numpy", "torch", "chumpy", "hamer"]
OPTIONAL_HAMER_IMPORTS = ["webdataset", "smplx", "timm", "pytorch_lightning", "yacs"]

REQUIRED_FILES = [
    PROJECT_ROOT / "inputs" / "exo.jpg",
    PROJECT_ROOT / "outputs" / "depth_raw.npy",
    PROJECT_ROOT / "outputs" / "exo_point_cloud.ply",
    PROJECT_ROOT / "outputs" / "hand_bboxes.json",
    PROJECT_ROOT / "outputs" / "hand_bbox_debug.png",
    PROJECT_ROOT / "outputs" / "hand_crops",
    PROJECT_ROOT / "external" / "hamer",
    PROJECT_ROOT / "external" / "hamer" / "hamer",
    PROJECT_ROOT / "external" / "hamer" / "demo.py",
    PROJECT_ROOT / "external" / "hamer" / "setup.py",
    PROJECT_ROOT / "external" / "hamer" / ".hamer" / "Scripts" / "python.exe",
    PROJECT_ROOT / "external" / "hamer" / "_DATA" / "data" / "mano" / "MANO_RIGHT.pkl",
    PROJECT_ROOT / "external" / "hamer" / "_DATA" / "data" / "mano" / "MANO_LEFT.pkl",
    PROJECT_ROOT / "external" / "hamer" / "_DATA" / "hamer_ckpts" / "checkpoints" / "hamer.ckpt",
    PROJECT_ROOT / "external" / "hamer" / "_DATA" / "data" / "mano_mean_params.npz",
]


def run_subprocess_imports(python_executable: Path, package_names: List[str]) -> Dict[str, bool]:
    results: Dict[str, bool] = {}
    if not python_executable.exists():
        return {package_name: False for package_name in package_names}
    for package_name in package_names:
        command = [str(python_executable), "-c", f"import {package_name}"]
        try:
            subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            results[package_name] = True
        except (subprocess.CalledProcessError, FileNotFoundError):
            results[package_name] = False
    return results


def check_files() -> List[Tuple[Path, bool]]:
    return [(path, path.exists()) for path in REQUIRED_FILES]


def format_status(name: str, status: bool) -> str:
    return f"[{'PASS' if status else 'FAIL'}] {name}"


def env_report(main_python: Path, hamer_python: Path, results: Dict[str, object]) -> str:
    lines: List[str] = []
    lines.append("# EgoWorld Stage 1 Environment Report")
    lines.append("")
    lines.append(f"Generated by: {main_python}")
    lines.append(f"Project root: {PROJECT_ROOT}")
    lines.append("")
    lines.append("## File existence")
    lines.append("")
    for path, exists in results["files"]:
        lines.append(format_status(str(path.relative_to(PROJECT_ROOT)), exists))
    lines.append("")
    lines.append("## Main environment imports")
    lines.append("")
    for package, passed in results["main_imports"].items():
        lines.append(format_status(package, passed))
    lines.append("")
    lines.append("## HaMeR environment imports")
    lines.append("")
    for package, passed in results["hamer_imports"].items():
        lines.append(format_status(package, passed))
    lines.append("")
    lines.append("## Optional HaMeR dependency imports")
    lines.append("")
    for package, passed in results["optional_hamer_imports"].items():
        lines.append(format_status(package, passed))
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    notes = [
        "- This script does not install missing packages.",
        "- If a dependency is missing, install it manually in the appropriate environment.",
        "- The main .venv environment is for Stage 1 logic; the HaMeR .hamer environment is for HaMeR-specific inference.",
    ]
    lines.extend(notes)
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check EgoWorld Stage 1 workspace state.")
    parser.add_argument(
        "--write-report",
        action="store_true",
        help="Write outputs/environment_report.md. By default this script only prints diagnostics.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    print("Checking project state for EgoWorld Stage 1...")
    print(f"Project root: {PROJECT_ROOT}")
    print(f"Main Python executable: {sys.executable}")

    main_python = Path(sys.executable)
    hamer_python = PROJECT_ROOT / "external" / "hamer" / ".hamer" / "Scripts" / "python.exe"
    files = check_files()
    print("\nFile checks:")
    for path, exists in files:
        print(format_status(str(path.relative_to(PROJECT_ROOT)), exists))

    if not hamer_python.exists():
        print(f"[FAIL] HaMeR python missing: {hamer_python}")

    print("\nMain environment import checks:")
    main_import_results = run_subprocess_imports(main_python, MAIN_IMPORTS)
    for package, passed in main_import_results.items():
        print(format_status(package, passed))

    print("\nHaMeR environment import checks:")
    hamer_import_results = run_subprocess_imports(hamer_python, HAMER_IMPORTS)
    for package, passed in hamer_import_results.items():
        print(format_status(package, passed))

    print("\nOptional HaMeR dependency checks:")
    optional_hamer_import_results = run_subprocess_imports(hamer_python, OPTIONAL_HAMER_IMPORTS)
    for package, passed in optional_hamer_import_results.items():
        print(format_status(package, passed))

    report_data = {
        "files": files,
        "main_imports": main_import_results,
        "hamer_imports": hamer_import_results,
        "optional_hamer_imports": optional_hamer_import_results,
    }
    markdowntxt = env_report(main_python, hamer_python, report_data)
    if args.write_report:
        try:
            OUTPUT_MARKDOWN.parent.mkdir(parents=True, exist_ok=True)
            OUTPUT_MARKDOWN.write_text(markdowntxt, encoding="utf-8")
            print(f"\nEnvironment report written to: {OUTPUT_MARKDOWN}")
        except Exception as exc:
            print(f"Failed to write markdown report: {exc}")
    else:
        print("\nRead-only check complete. Pass --write-report to save outputs/environment_report.md.")


if __name__ == "__main__":
    main()
